name: Check & fix styling (prettier)

on:
  push:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allows committing changes

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run prettier
        uses: permafrost-dev/prettier-docker-ga@main
        with:
          args: --config prettier.config.js "./**/*" "!./.github/**/*"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
        continue-on-error: true
