name: Run Linter

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run formatter
        run: npm run lint || true

      - name: Check linting status
        run: echo $?  # Print the exit code of the previous step

      - name: Report Status
        uses: EnricoMi/publish-unit-test-results@v3  # Or a similar action
        with:
          check_name: Linting
          test_results: ${{ success() }}  # "success" for exit code 0, "failure" for anything else
