name: SEO

on:
  pull_request:
  push:
    branches:
      - '**'
jobs:
  update-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19' # Specify the Node.js version

      - name: Install dependencies
        run: npm install xml2js

      - name: Run the sitemap update script
        run: npm run check-tools

      - name: Commit updated sitemap
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add sitemap.xml
          git commit -m 'Update sitemap'
          git push
        # This step requires that you have a token with write access to the repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
