name: Update Sitemap on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  update-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run the sitemap update script
        run: npm run check-tools

      - name: Commit updated sitemap
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add sitemap.xml
          git commit -m 'Update sitemap with new tools'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
